# Site settings
title: "The Gotten Framework"
url: "https://g0tten.github.io"
baseurl: "/video"
description: "Generic MDE framework fOr meTamorphic TEstiNg"
#gtag: "UA-61793148-6"
gtag: "G-JKMPYJFGYJ"
favicon: "/images/favicon.ico"
show_downloads: true

github:
  is_project_page: true
  repository_url: https://github.com/g0tten
  repository_name: Gotten
  owner_url: https://g0tten.github.io
  owner_name: g0tten

navbar:
  - name: Gotten
    link: /gotten
  - name: Update-site
    link: /gotten/update-site
  - name: Standalone Eclipse+Gotten
    link: /video
    subitems:
      - name: Windows version
        link: https://www.dropbox.com/s/fcv7cjkhlvk5yah/eclipse.zip?dl=0
      - name: Ubuntu version
        link: https://www.dropbox.com/s/t30w6kx1y41ik4d/eclipse.zip?dl=0
  - name: Ubuntu 20.04 VirtualBox VM+Gotten
    link: https://www.dropbox.com/s/m4s7rjk1tywl8cf/Ubuntu-20.04.x64-Gotten.zip?dl=0
  - name: Gotten for Cloud
    link: /evaluation
    subitems:
      - name: Simple project
        link: https://github.com/g0tten/sample/zipball/main
      - name: Evaluation project
        link: https://github.com/g0tten/evaluation/zipball/main
  - name: Gotten for Video Streaming APIs
    link: /video
    subitems:
      - name: YouTube
        link: https://github.com/g0tten/video/zipball/main
      - name: Vimeo
        link: https://github.com/g0tten/video/zipball/main
  
# Build settings
markdown: kramdown

theme: jekyll-theme-architect
encoding: utf-8

exclude:
  - CONTRIBUTING.md
  - .github
  - .gitignore

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mentions
  - include-markdown
  - jemoji

############# IMAGE PATHS #############

# if you want the images to be prefaced with a specific path, insert it here. Don't include a trailing slash at the end.
# the image include will insert this path before the image file name and will also add a /.
image_path: images

############# DEFAULTS #############
# you can define default frontmatter values here. you can narrow the type down with subfolders (e.g., docs/myfolder).
# you might want to list your sidebar and product as default frontmatter values
# with translation, change topnav, footer (and sidebar) to use topnav_ja, footer_ja, generic_ja etc. for Japanese, or _de for german. you must have corresponding
# data files with those _ja or _de file names. Read more in jekyllhowto-localization.html.
defaults:
  -
    scope:
      path: "images"
    values:
      image: true

webrick:
  headers:
    keywords: "Metamorphic testing,Model-driven engineering,Domain-specific languages,Cloud computing,Simulation"
